-- Active: 1784104426994@@127.0.0.1@5432@linkcare_temp@public

--** ENUM **--
CREATE TYPE DayPeriod AS ENUM ('MORNING','EVENING');
CREATE TYPE MealType AS ENUM ('BREAKFAST','LUNCH','DINNER');
CREATE TYPE MealTiming AS ENUM ('BEFORE','AFTER');

-- 블링
CREATE TYPE ExerciseTime AS ENUM ('t0', 't30', 't60', 't120');
CREATE TYPE MealStatus AS ENUM ('PENDING', 'COMPLETE', 'SKIPPED');

--** 사용자 **--
-- 사용자
DROP TABLE IF EXISTS "User";
CREATE TABLE "User" (
	"id"	INT GENERATED BY DEFAULT AS IDENTITY,
	"email"	TEXT 	NOT NULL UNIQUE,
	"password"	TEXT		NOT NULL,
	"loginCnt"	INT	DEFAULT 0	NOT NULL,
	"createdAt" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
);

COMMENT ON COLUMN "User"."id" IS 'autoincrement';
COMMENT ON COLUMN "User"."loginCnt" IS 'default:0, 최초 로그인 사용자 구분';

-- 프로필
DROP TABLE IF EXISTS "Profile";
CREATE TABLE "Profile" (
	"id"	INT GENERATED BY DEFAULT AS IDENTITY,
	"userId"	INT		NOT NULL,
	"gender"	TEXT		NULL,
	"nickName"	TEXT		NULL,
	"birthDate"	DATE		NULL,
	"height"	REAL		NULL,
	"goalWeight"	REAL		NULL,
	"goalCalorie"	INT		NULL,
	"createdAt" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NULL
);

COMMENT ON COLUMN "Profile"."id" IS 'autoincrement';


--** 식사 **--
-- 식사
DROP TABLE IF EXISTS "Meal";
CREATE TABLE "Meal" (
	"id"	INT GENERATED BY DEFAULT AS IDENTITY,
	"userId"	INT		NOT NULL,
	"mealType"	MealType		NOT NULL,
	"mealDate"	Date		NOT NULL,
	"goalCalorie"	INT		NULL,
	"unitCalorie"	INT		NULL,
	"photoUrl"	TEXT		NULL,
	"mealStatus"	MealStatus	DEFAULT 'PENDING'	NOT NULL,
	"createdAt" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NULL
);

COMMENT ON COLUMN "Meal"."id" IS 'autoincrement';
COMMENT ON COLUMN "Meal"."mealType" IS 'breakfast, lunch, dinner';
COMMENT ON COLUMN "Meal"."mealStatus" IS 'default: pending / pending, completed, skipped';

-- 식사 음식 --
DROP TABLE IF EXISTS "MealFood";
CREATE TABLE "MealFood" (
	"id"	INT GENERATED BY DEFAULT AS IDENTITY,
	"mealId"	INT		NOT NULL,
	"FoodName"	TEXT		NOT NULL,
	"calorie"	INT		NOT NULL
);

COMMENT ON COLUMN "MealFood"."id" IS 'autoincrement';


--** 매일관리 **--
-- 체중
DROP TABLE IF EXISTS "Weight";
CREATE TABLE "Weight" (
	"id"	INT GENERATED BY DEFAULT AS IDENTITY,
	"userId"	INT		NOT NULL,
	"weight"	REAL		NOT NULL,
	"weightDate"	DATE		NOT NULL,
	"bmi"	REAL		NULL,
	"createdAt" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
);

COMMENT ON COLUMN "Weight"."id" IS 'autoincrement';

-- 혈당
DROP TABLE IF EXISTS "BloodGlucose";
CREATE TABLE "BloodGlucose" (
	"id"	INT GENERATED BY DEFAULT AS IDENTITY,
	"userId"	INT		NOT NULL,
	"glucose"	INT		NOT NULL,
	"mealType"	MealType		NOT NULL,
	"mealTiming"	MealTiming		NOT NULL,
	"createdAt" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"bgDate"	DATE		NOT NULL
);

COMMENT ON COLUMN "BloodGlucose"."id" IS 'autoincrement';
COMMENT ON COLUMN "BloodGlucose"."mealType" IS 'breakfast,lunch,dinner';
COMMENT ON COLUMN "BloodGlucose"."mealTiming" IS 'before, after';

-- 혈압
DROP TABLE IF EXISTS "BloodPressure";
CREATE TABLE "BloodPressure" (
	"id"	INT GENERATED BY DEFAULT AS IDENTITY,
	"userId"	INT		NOT NULL,
	"systolic"	INT		NOT NULL,
	"diastolic"	INT		NOT NULL,
	"pulse"	INT		NULL,
	"dayPeriod"	DayPeriod		NOT NULL,
	"bpDate"	Date		NOT NULL,
	"createdAt" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NULL
);

COMMENT ON COLUMN "BloodPressure"."id" IS 'autoincrement';
COMMENT ON COLUMN "BloodPressure"."dayPeriod" IS 'morning, evening';

--** 데일리 쉴드 **--
-- 데일리 쉴드 --
DROP TABLE IF EXISTS "DailyShield";
CREATE TABLE "DailyShield" (
	"id"	INT GENERATED BY DEFAULT AS IDENTITY,
	"userId"	INT		NOT NULL,
	"dailyDate"	TEXT		NOT NULL,
	"feel"	INT		NULL,
	"energy"	INT		NULL,
	"isExercise"	Boolean	 DEFAULT FALSE	NOT NULL,
	"exersiseTime"	ExerciseTime	DEFAULT 't30'	NOT NULL,
	"exersiseType"	TEXT		NULL,
	"isWater"	Boolean	DEFAULT FALSE	NULL,
	"waterCup"	INT		NULL,
	"isSupplement"	Boolean	 DEFAULT FALSE	NOT NULL,
	"supplementType"	TEXT		NULL,
	"createdAt" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NULL
);

COMMENT ON COLUMN "DailyShield"."id" IS 'autoincrement';
COMMENT ON COLUMN "DailyShield"."feel" IS '1: 힘듦, 2: 별로, 3: 무난, 4:  좋음, 5: 최고';
COMMENT ON COLUMN "DailyShield"."energy" IS '1: 지침,  2: 부족, 3: 충분, 4: 활력';
COMMENT ON COLUMN "DailyShield"."isExercise" IS 'default:false';
COMMENT ON COLUMN "DailyShield"."exersiseTime" IS 'default: t30';
COMMENT ON COLUMN "DailyShield"."exersiseType" IS '걷기, 달리기, 등산, 자전거, 수영, 헬스, 크로스핏, 요가, 필라테스, 스트레칭, 홈트레이닝, 구기 스포츠, 댄스, 기타';
COMMENT ON COLUMN "DailyShield"."isWater" IS 'default:false';
COMMENT ON COLUMN "DailyShield"."waterCup" IS 'default: 0';
COMMENT ON COLUMN "DailyShield"."isSupplement" IS 'default:false';
COMMENT ON COLUMN "DailyShield"."supplementType" IS '종합비타민, 비타민C, 비타민D, 비타민B군, 오메가3, 프로바이오틱스, 마그네슘, 칼슘, 아연, 철분, 밀크씨슬, 루테인, 코엔자임Q10, 콜라겐, 글루코사민, 홍삼, 프로틴, 커큐민, 엽산, 기타';


--** 검진 **--
-- 검진 결과
DROP TABLE IF EXISTS "CheckUp";
CREATE TABLE "CheckUp" (
	"id"	INT GENERATED BY DEFAULT AS IDENTITY,
	"userId"	INT		NOT NULL,
	"height"	REAL		NULL,
	"weight"	REAL		NULL,
	"waist"	REAL		NULL,
	"bmi"	REAL		NULL,
	"visionLeft"	REAL		NULL,
	"visionRight"	REAL		NULL,
	"hearing"	TEXT		NULL,
	"bp_systolic"	INT		NULL,
	"bp_diastolic"	INT		NULL,
	"urine_protein"	TEXT		NULL,
	"hemoglobin"	REAL		NULL,
	"fbg"	INT		NULL,
	"creatinine"	REAL		NULL,
	"egfr"	INT		NULL,
	"ast"	INT		NULL,
	"alt"	INT		NULL,
	"ygtp"	INT		NULL,
	"year"	INT		NULL,
	"checkUpDate"	DATE	NOT NULL,
	"isShow"	BOOLEAN		DEFAULT TRUE	NOT NULL,
	"createdAt" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
);

COMMENT ON COLUMN "CheckUp"."id" IS 'autoincrement';
COMMENT ON COLUMN "CheckUp"."height" IS '신장';
COMMENT ON COLUMN "CheckUp"."weight" IS '체중';
COMMENT ON COLUMN "CheckUp"."waist" IS '허리둘레';
COMMENT ON COLUMN "CheckUp"."bmi" IS 'BMI';
COMMENT ON COLUMN "CheckUp"."visionLeft" IS '시력(좌)';
COMMENT ON COLUMN "CheckUp"."visionRight" IS '시력(우)';
COMMENT ON COLUMN "CheckUp"."hearing" IS '청력(좌/우)';
COMMENT ON COLUMN "CheckUp"."bp_systolic" IS '혈압(수축기)';
COMMENT ON COLUMN "CheckUp"."bp_diastolic" IS '혈압(이완기)';
COMMENT ON COLUMN "CheckUp"."urine_protein" IS '신장기능-요단백';
COMMENT ON COLUMN "CheckUp"."hemoglobin" IS '혈색소';
COMMENT ON COLUMN "CheckUp"."fbg" IS '공복혈당';
COMMENT ON COLUMN "CheckUp"."creatinine" IS '신장기능-혈청크레아티닌';
COMMENT ON COLUMN "CheckUp"."egfr" IS '신장기능-신사구체여과율';
COMMENT ON COLUMN "CheckUp"."ast" IS '간기능-에이에스티';
COMMENT ON COLUMN "CheckUp"."alt" IS '간기능-에이엘티';
COMMENT ON COLUMN "CheckUp"."ygtp" IS '간기능-감미지티피';
COMMENT ON COLUMN "CheckUp"."checkUpDate" IS '검진 날짜';
COMMENT ON COLUMN "CheckUp"."isShow" IS 'default true';

-- 검진 코멘트
DROP TABLE IF EXISTS "CheckUpComment";
CREATE TABLE "CheckUpComment" (
	"id"	INT GENERATED BY DEFAULT AS IDENTITY,
	"checkUpId"	INT		NOT NULL,
	"comment"	TEXT		NOT NULL
);

COMMENT ON COLUMN "CheckUpComment"."id" IS 'autoincrement';

-- 검진 정규화
DROP TABLE IF EXISTS "CheckupAssessment";
CREATE TABLE "CheckupAssessment" (
	"id"	INT GENERATED BY DEFAULT AS IDENTITY,
	"checkUpId"	INT		NOT NULL,
	"waist"	TEXT		NOT NULL,
	"bmi"	TEXT		NOT NULL,
	"bp"	TEXT		NOT NULL,
	"urine_protein"	TEXT		NOT NULL,
	"hemoglobin"	TEXT		NOT NULL,
	"fbg"	TEXT		NOT NULL,
	"creatinine"	TEXT		NOT NULL,
	"egfr"	TEXT		NOT NULL,
	"ast"	TEXT		NOT NULL,
	"alt"	TEXT		NOT NULL,
	"ygtp"	TEXT		NOT NULL
);

COMMENT ON COLUMN "CheckupAssessment"."id" IS 'autoincrement';


--** PK **--
ALTER TABLE "Weight" ADD CONSTRAINT "PK_WEIGHT" PRIMARY KEY ("id");

ALTER TABLE "Profile" ADD CONSTRAINT "PK_PROFILE" PRIMARY KEY ("id");

ALTER TABLE "MealFood" ADD CONSTRAINT "PK_MEALFOOD" PRIMARY KEY ("id");

ALTER TABLE "CheckUpComment" ADD CONSTRAINT "PK_CHECKUPCOMMENT" PRIMARY KEY ("id", "checkUpId");

ALTER TABLE "CheckupAssessment" ADD CONSTRAINT "PK_CHECKUPASSESSMENT" PRIMARY KEY ("id", "checkUpId");

ALTER TABLE "BloodGlucose" ADD CONSTRAINT "PK_BLOODGLUCOSE" PRIMARY KEY ("id");

ALTER TABLE "DailyShield" ADD CONSTRAINT "PK_DAILYSHIELD" PRIMARY KEY ("id");

ALTER TABLE "User" ADD CONSTRAINT "PK_USER" PRIMARY KEY ("id");

ALTER TABLE "Meal" ADD CONSTRAINT "PK_MEAL" PRIMARY KEY ("id");

ALTER TABLE "CheckUp" ADD CONSTRAINT "PK_CHECKUP" PRIMARY KEY ("id");

ALTER TABLE "BloodPressure" ADD CONSTRAINT "PK_BLOODPRESSURE" PRIMARY KEY ("id");

--** FK **--
ALTER TABLE "Profile" ADD CONSTRAINT "FK_User_TO_Profile_1" FOREIGN KEY ("userId")
REFERENCES "User" ("id")
ON DELETE CASCADE;

--
ALTER TABLE "CheckUp" ADD CONSTRAINT "FK_User_TO_CheckUp_1" FOREIGN KEY ("userId")
REFERENCES "User" ("id")
ON DELETE CASCADE;

ALTER TABLE "CheckUpComment" ADD CONSTRAINT "FK_CheckUp_TO_CheckUpComment_1" FOREIGN KEY ("checkUpId")
REFERENCES "CheckUp" ("id")
ON DELETE CASCADE;

ALTER TABLE "CheckupAssessment" ADD CONSTRAINT "FK_CheckUp_TO_CheckupAssessment_1" FOREIGN KEY ("checkUpId")
REFERENCES "CheckUp" ("id")
ON DELETE CASCADE;

--
ALTER TABLE "Weight" ADD CONSTRAINT "FK_User_TO_Weight_1" FOREIGN KEY ("userId")
REFERENCES "User" ("id")
ON DELETE CASCADE;

ALTER TABLE "BloodGlucose" ADD CONSTRAINT "FK_User_TO_BloodGlucose_1" FOREIGN KEY ("userId")
REFERENCES "User" ("id")
ON DELETE CASCADE;

ALTER TABLE "BloodPressure" ADD CONSTRAINT "FK_User_TO_BloodPressure_1" FOREIGN KEY ("userId")
REFERENCES "User" ("id")
ON DELETE CASCADE;

--
ALTER TABLE "DailyShield" ADD CONSTRAINT "FK_User_TO_DailyShield_1" FOREIGN KEY ("userId")
REFERENCES "User" ("id")
ON DELETE CASCADE;

ALTER TABLE "Meal" ADD CONSTRAINT "FK_User_TO_Meal_1" FOREIGN KEY ("userId")
REFERENCES "User" ("id")
ON DELETE CASCADE;

ALTER TABLE "MealFood" ADD CONSTRAINT "FK_Meal_TO_MealFood_1" FOREIGN KEY ("mealId")
REFERENCES "Meal" ("id")
ON DELETE CASCADE;


--** Unique **--
ALTER TABLE "CheckUp" ADD CONSTRAINT "UK_CHECKUP_USER_YEAR" UNIQUE ("userId", "year");

ALTER TABLE "Weight" ADD CONSTRAINT "UK_WEIGHT_USER_DATE" UNIQUE ("userId", "weightDate");

ALTER TABLE "BloodPressure" ADD CONSTRAINT "UK_BP_USER_PERIOD_DATE" UNIQUE ("userId","dayPeriod","bpDate");

ALTER TABLE "BloodGlucose" ADD CONSTRAINT "UK_BLOODGLUCOSE_USER_DATE" UNIQUE ("userId","bgDate","mealType","mealTiming");

ALTER TABLE "Meal" ADD CONSTRAINT "UK_MEAL_USER_DATE_TYPE" UNIQUE ("userId", "mealDate", "mealType");

ALTER TABLE "DailyShield" ADD CONSTRAINT "UK_SHIELD_USER_DATE" UNIQUE ("userId", "dailyDate");


--** updateAt trigger **--
-- updateAt 공용 함수 생성 (DB에 단 한 번만 생성)
CREATE OR REPLACE FUNCTION update_modified_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW."updatedAt" = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_profile_modtime
    BEFORE UPDATE ON "Profile"
    FOR EACH ROW
    EXECUTE FUNCTION update_modified_column();

CREATE TRIGGER update_meal_modtime
    BEFORE UPDATE ON "Meal"
    FOR EACH ROW
    EXECUTE FUNCTION update_modified_column();

CREATE TRIGGER update_bloodPressure_modtime
    BEFORE UPDATE ON "BloodPressure"
    FOR EACH ROW
    EXECUTE FUNCTION update_modified_column();

CREATE TRIGGER update_dailyShield_modtime
    BEFORE UPDATE ON "DailyShield"
    FOR EACH ROW
    EXECUTE FUNCTION update_modified_column();